"""SQLAlchemy model for the ``audits`` table.

Each row represents a single audit run against a dataset snapshot.  The
lifecycle of an audit is tracked via the ``status`` column, which transitions
through ``pending`` → ``running`` → ``completed`` (or ``failed``) as the
analysis pipeline executes asynchronously in the background.

Design notes
------------
* ``status`` uses a native PostgreSQL ``ENUM`` type so that the database
  enforces the valid state machine values without application-layer guards
  on every write path.  The enum is defined with a name (``audit_status``)
  so Alembic emits a ``CREATE TYPE`` statement in the migration and the
  type can be referenced by name in future DDL.
* ``parameters`` stores caller-supplied audit configuration (e.g. a
  ``dormant_threshold_days`` override) as JSONB.  Using JSONB rather than
  a flat set of nullable columns keeps the schema stable across future
  parameter additions without requiring additional migrations.
* ``summary`` is nullable JSONB — it is ``NULL`` while the audit is pending
  or running, and is written atomically when the pipeline marks the audit
  as ``completed`` or ``failed``.
* ``started_at`` and ``completed_at`` are nullable because they are
  populated progressively: ``started_at`` is set when the background task
  begins processing, ``completed_at`` when it terminates (regardless of
  outcome).  Both carry timezone information so UTC comparisons are
  unambiguous.
* ``created_at`` uses a database-side ``server_default`` so the value is
  authoritative even for rows inserted outside the ORM (e.g. test fixtures,
  migration seed data).
"""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import TYPE_CHECKING

from sqlalchemy import DateTime, Enum, ForeignKey, func, text
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import Base

if TYPE_CHECKING:
    from app.models.dataset import Dataset
    from app.models.finding import Finding

# ---------------------------------------------------------------------------
# Status enum
# ---------------------------------------------------------------------------

#: Valid lifecycle states for an audit run.  Modelled as a named PostgreSQL
#: ENUM type so the database enforces valid values without requiring
#: application-level guards on every write path.
AUDIT_STATUS_ENUM = Enum(
    "pending",
    "running",
    "completed",
    "failed",
    name="audit_status",
    create_constraint=True,
)


# ---------------------------------------------------------------------------
# Model
# ---------------------------------------------------------------------------


class Audit(Base):
    """Persisted audit run linked to a specific dataset snapshot.

    Attributes
    ----------
    id:
        UUIDv4 primary key generated by the application before INSERT so
        that callers know the audit ID before the transaction is committed.
    dataset_id:
        Foreign key referencing the ``datasets`` table.  An audit is always
        associated with exactly one dataset snapshot.  Deleting the parent
        dataset cascades to this row.
    status:
        Current lifecycle state.  Transitions follow the state machine:
        ``pending`` (created, not yet started) → ``running`` (pipeline
        executing) → ``completed`` (findings persisted, summary written)
        or ``failed`` (pipeline encountered an unrecoverable error).
    parameters:
        Caller-supplied configuration for this audit run, stored as JSONB
        so that future parameter additions do not require schema changes.
        Typical contents: ``{ "dormant_threshold_days": 45 }``.
        Defaults to an empty object when the caller provides no overrides.
    summary:
        Aggregate statistics written by the pipeline upon completion.
        ``NULL`` while the audit is pending or running.  Expected shape
        once populated::

            {
                "total_users_analyzed": 100,
                "total_findings": 12,
                "findings_by_category": {
                    "overprivileged": 7,
                    "dormant_privileged": 5
                },
                "findings_by_severity": {
                    "critical": 3,
                    "high": 4,
                    "medium": 4,
                    "low": 1
                }
            }

    started_at:
        UTC timestamp recorded when the background pipeline task begins
        processing.  ``NULL`` until the task acquires the audit record.
    completed_at:
        UTC timestamp recorded when the pipeline terminates — whether
        the outcome is ``completed`` or ``failed``.
    created_at:
        UTC timestamp set by the database server on INSERT.
    """

    __tablename__ = "audits"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        server_default=text("gen_random_uuid()"),
        comment="Unique audit identifier (UUIDv4).",
    )
    dataset_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("datasets.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        comment="Foreign key to the dataset snapshot this audit analyses.",
    )
    status: Mapped[str] = mapped_column(
        AUDIT_STATUS_ENUM,
        nullable=False,
        default="pending",
        server_default="pending",
        index=True,
        comment="Current lifecycle state (pending/running/completed/failed).",
    )
    parameters: Mapped[dict] = mapped_column(
        JSONB,
        nullable=False,
        default=dict,
        server_default=text("'{}'"),
        comment="Caller-supplied audit configuration overrides stored as JSONB.",
    )
    summary: Mapped[dict | None] = mapped_column(
        JSONB,
        nullable=True,
        comment="Aggregate finding statistics written by the pipeline on completion.",
    )
    started_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        comment="UTC timestamp when the audit pipeline began processing.",
    )
    completed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        comment="UTC timestamp when the audit pipeline terminated (success or failure).",
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        comment="UTC timestamp of audit record creation.",
    )

    # ------------------------------------------------------------------
    # Relationships
    # ------------------------------------------------------------------

    #: Back-reference to the parent dataset.  Lazy-loaded by default;
    #: use ``joinedload(Audit.dataset)`` in queries that need it eagerly.
    dataset: Mapped[Dataset] = relationship(
        "Dataset",
        back_populates="audits",
        lazy="select",
    )

    #: All findings produced by this audit run.  Cascade delete ensures
    #: findings are removed automatically when their parent audit is deleted.
    findings: Mapped[list[Finding]] = relationship(
        "Finding",
        back_populates="audit",
        cascade="all, delete-orphan",
        lazy="select",
    )

    def __repr__(self) -> str:  # pragma: no cover
        return (
            f"Audit(id={self.id!r}, dataset_id={self.dataset_id!r}, "
            f"status={self.status!r}, created_at={self.created_at!r})"
        )
