"""SQLAlchemy model for the ``findings`` table.

Each row represents a single audit finding produced by the analysis
pipeline for a given audit run.  Findings are always child records of an
``Audit`` and are deleted automatically when their parent audit is removed
(cascade delete).

Design notes
------------
* ``category`` and ``severity`` use named PostgreSQL ENUM types
  (``finding_category`` and ``finding_severity``) so the database enforces
  valid values at the storage layer, consistent with the ``audit_status``
  enum used in ``audits``.
* ``role_assignments`` and ``evidence`` are JSONB columns.  Storing them as
  JSONB rather than flat columns keeps the schema stable across future
  changes to what the pipeline captures — adding a new evidence field does
  not require a migration.
* ``principal_type`` is a plain ``VARCHAR`` rather than an enum because the
  set of principal types (``user``, ``service_principal``, ``group``) could
  expand without a schema change, and the LLM pipeline should not be gated
  on DDL alterations for minor taxonomy additions.
* ``remediation`` and ``narrative`` are ``TEXT`` columns rather than
  ``VARCHAR`` because LLM-generated content is unbounded in length and
  VARCHAR limits would silently truncate long outputs.
* ``created_at`` uses a database-side ``server_default`` so the value is
  authoritative even for rows inserted outside the ORM (e.g. test fixtures
  or migration seed scripts).
"""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import TYPE_CHECKING

from sqlalchemy import DateTime, Enum, ForeignKey, String, Text, func, text
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import Base

if TYPE_CHECKING:
    from app.models.audit import Audit

# ---------------------------------------------------------------------------
# Enum types
# ---------------------------------------------------------------------------

#: Valid finding categories.  Phase 1 covers two categories; the name is
#: stable so future categories can be added via ``ALTER TYPE … ADD VALUE``
#: without recreating the type.
FINDING_CATEGORY_ENUM = Enum(
    "overprivileged",
    "dormant_privileged",
    name="finding_category",
    create_constraint=True,
)

#: Valid severity tiers ordered from most to least severe.
FINDING_SEVERITY_ENUM = Enum(
    "critical",
    "high",
    "medium",
    "low",
    name="finding_severity",
    create_constraint=True,
)


# ---------------------------------------------------------------------------
# Model
# ---------------------------------------------------------------------------


class Finding(Base):
    """A single security finding produced by the audit pipeline.

    Attributes
    ----------
    id:
        UUIDv4 primary key generated by the application before INSERT so
        that the caller knows the finding ID before the transaction is
        committed.
    audit_id:
        Foreign key referencing the parent ``audits`` record.  Deleting
        the parent audit cascades to all its findings.
    category:
        Classification of the finding.  One of ``overprivileged`` or
        ``dormant_privileged`` in Phase 1.
    severity:
        Risk tier assigned by the LLM analysis pipeline.  One of
        ``critical``, ``high``, ``medium``, or ``low``.
    principal_id:
        The Azure AD object ID (or equivalent synthetic identifier) of the
        affected user, service principal, or group.  Stored as a plain
        string rather than a UUID because Azure AD object IDs are UUIDs
        but may be synthesised differently in the test dataset.
    principal_name:
        Human-readable display name of the affected principal, e.g.
        ``"Alice Johnson"`` or ``"svc-backup-agent"``.
    principal_type:
        Category of the principal: typically ``user``, ``service_principal``,
        or ``group``.  Not enforced at the database level to accommodate
        future principal types without schema changes.
    role_assignments:
        JSONB array of the specific role assignments relevant to this
        finding.  Each element is expected to carry at least:
        ``{ "roleId": "...", "roleName": "...", "assignmentType": "...",
        "assignedAt": "..." }``.
    evidence:
        JSONB object containing the supporting signals that led to this
        finding, e.g.::

            {
                "days_since_last_signin": 92,
                "privileged_role_count": 4,
                "dormant_threshold_days": 30
            }

    remediation:
        Plain-language recommended action for remediating the finding,
        e.g. ``"Remove the Global Administrator role assignment and
        re-evaluate whether User Administrator is still required."``
    narrative:
        LLM-generated 2–4 sentence explanation of why the finding is a
        risk and what remediation achieves.  Intended for direct inclusion
        in tickets or executive summaries.
    created_at:
        UTC timestamp set by the database server on INSERT.
    """

    __tablename__ = "findings"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        server_default=text("gen_random_uuid()"),
        comment="Unique finding identifier (UUIDv4).",
    )
    audit_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("audits.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        comment="Foreign key to the parent audit run.",
    )
    category: Mapped[str] = mapped_column(
        FINDING_CATEGORY_ENUM,
        nullable=False,
        index=True,
        comment="Finding category (overprivileged or dormant_privileged).",
    )
    severity: Mapped[str] = mapped_column(
        FINDING_SEVERITY_ENUM,
        nullable=False,
        index=True,
        comment="Risk severity tier (critical/high/medium/low).",
    )
    principal_id: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
        comment="Azure AD object ID of the affected principal.",
    )
    principal_name: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
        comment="Display name of the affected principal.",
    )
    principal_type: Mapped[str] = mapped_column(
        String(64),
        nullable=False,
        comment="Principal type: user, service_principal, or group.",
    )
    role_assignments: Mapped[list] = mapped_column(
        JSONB,
        nullable=False,
        default=list,
        server_default=text("'[]'"),
        comment="JSON array of role assignment objects relevant to this finding.",
    )
    evidence: Mapped[dict] = mapped_column(
        JSONB,
        nullable=False,
        default=dict,
        server_default=text("'{}'"),
        comment="Supporting evidence signals (days since sign-in, role counts, etc.).",
    )
    remediation: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        comment="Recommended remediation action in plain language.",
    )
    narrative: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        comment="LLM-generated plain-language explanation of the finding and its risk.",
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        comment="UTC timestamp of finding creation.",
    )

    # ------------------------------------------------------------------
    # Relationships
    # ------------------------------------------------------------------

    #: Back-reference to the parent audit.  Lazy-loaded by default;
    #: use ``joinedload(Finding.audit)`` in queries that need it eagerly.
    audit: Mapped[Audit] = relationship(
        "Audit",
        back_populates="findings",
        lazy="select",
    )

    def __repr__(self) -> str:  # pragma: no cover
        return (
            f"Finding(id={self.id!r}, audit_id={self.audit_id!r}, "
            f"category={self.category!r}, severity={self.severity!r}, "
            f"principal_name={self.principal_name!r})"
        )
