"""SQLAlchemy model for the ``query_logs`` table.

Each row records a single natural-language query submitted against a dataset
snapshot, along with the structured data payload and plain-language summary
returned by the query service.  Query logs are retained for auditing and
debugging purposes — they allow engineers to review what questions were asked,
how the dataset was interpreted, and what answers were produced.

Design notes
------------
* ``structured_response`` is JSONB because the query engine returns a
  variable-shape payload depending on the question — it may be an array of
  user records, a scalar count, or a key/value summary.  JSONB keeps the
  schema stable across query types without requiring per-question DDL.
* ``natural_language_response`` is ``TEXT`` (unbounded) because LLM-generated
  prose can vary widely in length.  A ``VARCHAR`` limit would silently
  truncate long answers.
* ``question`` is also ``TEXT`` to accommodate arbitrarily long questions
  without imposing an artificial constraint.  In practice, questions will
  be short, but the storage cost of TEXT vs. VARCHAR is negligible.
* The foreign key references ``datasets.id`` with ``ON DELETE CASCADE`` so
  that removing a dataset also removes all query logs against it, keeping
  the database tidy without requiring application-layer cleanup logic.
* ``created_at`` uses a database-side ``server_default`` so the timestamp is
  authoritative even for rows inserted outside the ORM (e.g. test fixtures).
"""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import TYPE_CHECKING

from sqlalchemy import DateTime, ForeignKey, Text, func, text
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import Base

if TYPE_CHECKING:
    from app.models.dataset import Dataset


class QueryLog(Base):
    """Persisted record of a natural-language query and its response.

    Attributes
    ----------
    id:
        UUIDv4 primary key generated by the application before INSERT so
        that callers know the log ID before the transaction is committed.
    dataset_id:
        Foreign key referencing the ``datasets`` table.  A query is always
        issued against a specific dataset snapshot.  Deleting the parent
        dataset cascades to all associated query logs.
    question:
        The raw natural-language question submitted by the caller, stored
        verbatim.  No normalisation is applied so that the log faithfully
        represents what was asked.
    structured_response:
        JSONB payload returned by the query engine.  The shape varies by
        question type: it may be an array of matching principal records, a
        scalar value, or a structured summary object.  ``NULL`` is permitted
        for questions that the engine could not answer (graceful decline).
    natural_language_response:
        The plain-language summary answer produced by the LLM.  Stored as
        TEXT to accommodate variable-length LLM output.  ``NULL`` when the
        query engine declined to answer.
    created_at:
        UTC timestamp set by the database server on INSERT.
    """

    __tablename__ = "query_logs"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        server_default=text("gen_random_uuid()"),
        comment="Unique query log identifier (UUIDv4).",
    )
    dataset_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("datasets.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        comment="Foreign key to the dataset snapshot this query was issued against.",
    )
    question: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        comment="Raw natural-language question submitted by the caller.",
    )
    structured_response: Mapped[dict | None] = mapped_column(
        JSONB,
        nullable=True,
        comment="Structured data payload returned by the query engine (shape varies by question).",
    )
    natural_language_response: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        comment="Plain-language summary answer produced by the LLM.",
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        comment="UTC timestamp of query log creation.",
    )

    # ------------------------------------------------------------------
    # Relationships
    # ------------------------------------------------------------------

    #: Back-reference to the parent dataset.  Lazy-loaded by default;
    #: use ``joinedload(QueryLog.dataset)`` in queries that need it eagerly.
    dataset: Mapped[Dataset] = relationship(
        "Dataset",
        back_populates="query_logs",
        lazy="select",
    )

    def __repr__(self) -> str:  # pragma: no cover
        return (
            f"QueryLog(id={self.id!r}, dataset_id={self.dataset_id!r}, "
            f"question={self.question[:50]!r}, created_at={self.created_at!r})"
        )
